### PR TITLE
Create Homepage with three buttons (“Create Lobby”, “Join Lobby” and “Rules”), Create Rules page with "back" button and rules of the game.

### PR DESCRIPTION
**Pull request by mxkso**

### CODE REVIEW

**Comment by Meleac** [comment]
Did you use MUI for the buttons etc on your Homepage?

**Comment by mxkso** [comment]
> Did you use MUI for the buttons etc on your Homepage?

No, I created the buttons myself.

**Comment by felixmerz00** [comment]
On the phone it looks great. On my 13 inch notebook screen the text on the rules page goes beyond its container.

**Comment by mxkso** [comment]
Now, it is created with MUI.

**Pull request merged**
